# GatewayService/.github/workflows/ci.yml
name: CI - Gateway Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/GatewayService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Backend/GatewayService/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Backend/GatewayService
          npm install

      - name: Run Linter
        run: |
          cd Backend/GatewayService
          npm run lint

      - name: Run Tests
        run: |
          cd Backend/GatewayService
          npm test
          
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-cvk62cq4d50c73dk2i10?key=r6gQtstyo5w
